### ISSUE TITLE
Using Local Images on QS Server

### ISSUE THREAD

**Issue by scottduthie** [murraygm/qse-mgoimagegrid#3]
Hi Murray,

Great extension!

I am trying to use this on QS server, latest version, think it's 3.4.
Where is the extension looking to find the images folder on the server?
If I place the images in server location  C:\Program Files\Qlik\Sense\Client\assets\external\mgo\IMGs\IG then what part of this string do I need to use in the ImageGrid properties?

Thanks!

**Comment by murraygm** [comment]
Hi I haven't done an upgrade test on 3.2 yet but on 3.1 this would work as the path for 'Local' in the Image Source setting. 
../resources/assets/external/mgo/IMGs/IG

that resolves to https://[server]/resources/assets/external/mgo/IMGs/IG
if you can see an image placed there via the browser then they should be accessible.
Also if you set the property to use 'online' instead then the URL would work:
https://[server]/resources/assets/external/mgo/IMGs/IG/

this is the key folder to serving assets via Sense: https://[server]/resources/assets/external/
You should be able to serve any resource from here. If you are still having issues, create a new mashup project. That registers a folder that is accessible via a browser with the Sense server. Then add the images in that folder structure.
