### ISSUE TITLE
Images not showing when not on server

### ISSUE THREAD

**Issue by RelationMedia** [murraygm/qse-mgoimagegrid#6]
Hi, 

I have a problem with the MGO image extension. 

I use a dimension to display the images. The dimension is a column in Excel with direct links to the images. 
When I view the Dashboard from the Sense Server, the extensions works. But if I have a client look at the Dashboard the images wont display. 

Is there a workaround for this issue? 

Thanks,
Andreas

**Comment by murraygm** [comment]
Hi Andreas
I haven't come across this before. It could be one of a couple of things. 
1) The client's browser/security set up - if very strict it might be restricting assets from loading, I've seen that with iFrame use in single image mode, so possible it can also be at a cross domain asset use.
2) Something in the access rules on the Qlik server is restricting access for the client. Are the images being loaded as local or online resources? 
3) Client account on server may have access rules that are causing an issue - can you log in as them and test, or create an account with same permissions to test from?

**Comment by RelationMedia** [comment]
Hi Murraygm,

The problem was a login failure at the image host. The problem has now been resolved. Thank you for your response.
